In [7]:
import numpy
from sklearn.linear_model import LinearRegression

In [3]:
lm = LinearRegression()

In [15]:
x_train = numpy.array(range(20)).reshape((20, 1))
y_train = numpy.array(range(20,40)).reshape((20, 1))



In [16]:


lm.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [17]:
lm.intercept_

array([20.])

In [18]:
lm.coef_

array([[1.]])

In [20]:
x_test = numpy.array(range(100,120)).reshape(20,1)
predictions = lm.predict(x_test)

In [25]:
print((predictions-x_test))
x_test.

[[20.]
 [20.]
 [20.]
 [20.]
 [20.]
 [20.]
 [20.]
 [20.]
 [20.]
 [20.]
 [20.]
 [20.]
 [20.]
 [20.]
 [20.]
 [20.]
 [20.]
 [20.]
 [20.]
 [20.]]


In [ ]:
#could isolate certain variables and see 
# output r2 and some error values and give some simple explanations

In [26]:
%config IPCompleter.greedy=True
%config IPCompleter.

In [ ]:
#want the value of metrics.mean_absolute_error(t_test, predictions) to be almost 0